# 1) Importing Numpy

In [1]:
import numpy
a = numpy.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


    (OR)

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


# 2) Checking Version 

In [3]:
import numpy as np
print(np.__version__)

1.20.1


# 3) Type()

In [4]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 4) Creating array using Tuples

In [5]:
import numpy as np
a = np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]


# 5) 0 -Dimension

In [6]:
import numpy as np
a = np.array(34)
print(a)
print(f"The dimension of the above array is {a.ndim}")

34
The dimension of the above array is 0


# 6) 1- Dimension

In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(f"The dimension of the above array is {a.ndim}")

[1 2 3 4 5]
The dimension of the above array is 1


# 7) 2-Dimension

In [8]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(f"The dimension of the above array is {a.ndim}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The dimension of the above array is 2


# 8) 3-Dimension

In [9]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(f"The dimension of the above array is {a.ndim}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The dimension of the above array is 3


# 9) Higher Dimensional Array

In [10]:
import numpy as np
a = np.array([1,2,3,4,5],ndmin=5)
print(a)
print(f"The dimension of the above array is {a.ndim}")

[[[[[1 2 3 4 5]]]]]
The dimension of the above array is 5


# 10) Indexing in 1-D array

In [11]:
import numpy as np
b = np.array([1,2,3,4,5,6,7])
print(b)
print(f"To print first element of array {b[0]}")
print(f"To print second element of array {b[1]}")
print(f"To print third and fourth element of array {b[2]} and {b[3]}")
print(f"To print all element from third upto end of array {b[2:]}")

[1 2 3 4 5 6 7]
To print first element of array 1
To print second element of array 2
To print third and fourth element of array 3 and 4
To print all element from third upto end of array [3 4 5 6 7]


# 11) Indexing in 2-D array

In [12]:
import numpy as np
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(b)
print(f"To print first element of 1-D array {b[0,0]}")
print(f"To print second element of 2-D array {b[1,1]}")
print(f"To print third and fourth element of 2-D array {b[1,2]} and {b[1,3]}")
print(f"To print all element from third upto end from 1-D and 2_d array {b[:,2:]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
To print first element of 1-D array 1
To print second element of 2-D array 7
To print third and fourth element of 2-D array 8 and 9
To print all element from third upto end from 1-D and 2_d array [[ 3  4  5]
 [ 8  9 10]]


# 12) Indexing 3-D array

In [13]:
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"To print 5 and 8 form the given above array: {a[0,1,1]} and {a[1,0,1]}")


To print 5 and 8 form the given above array: 5 and 8


# 13) Indexing with negtaive sign

In [14]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"To print the last element of the above array {a[-1,-1]}")

To print the last element of the above array 10


# 14)Slicing

In [15]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"To print(2,3,4,5) is \n {a[0,1:]}")

To print(2,3,4,5) is 
 [2 3 4 5]


In [16]:
print(f"To print(3,4,5,8,9,10) is \n {a[:,2:]}")

To print(3,4,5,8,9,10) is 
 [[ 3  4  5]
 [ 8  9 10]]


In [17]:
print(f"To print all is \n {a[:,:]}")

To print all is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 15) Step in numpy

In [18]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"To print odd numbers \n {a[0::2]}")

To print odd numbers 
 [1 3 5 7 9]


# 16) Checking Datatype in array

In [19]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [20]:
import numpy as np
a = np.array(["NTS","Tejas","Manu"])
print(a)
print(a.dtype)

['NTS' 'Tejas' 'Manu']
<U5


# 17) Creating the array with a defined data type

In [21]:
import numpy as np
a = np.array([1,2,3,4,5],dtype="S")
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [22]:
import numpy as np
a = np.array([1,2,3,4,5],dtype="f")
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float32


# 18) Converting Data Type on Existing Arrays

In [23]:
import numpy as np
a = np.array([1.2,2.3,3.4,4.5,5.6])
b = a.astype('i')
print(a)
print(b)
print(a.dtype)
print(b.dtype)
print(type(a))
print(type(b))

[1.2 2.3 3.4 4.5 5.6]
[1 2 3 4 5]
float64
int32
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
import numpy as np
a = np.array([1,0,9,8,0])
b = a.astype('B')
print(a.dtype)
print(b.dtype)

int32
uint8


# 19) Copy() in numpy

In [25]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = a.copy()
a[3] = 44
print(a)
print(b)

[ 1  2  3 44  5  6  7]
[1 2 3 4 5 6 7]


In [26]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = a.copy()
b[3] = 4444
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[1 2 3 4 5 6 7]
[   1    2    3 4444    5    6    7]
int32
int32


# 20)View in Numpy

In [27]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = a.view()
a[3] = 44
print(a)
print(b)

[ 1  2  3 44  5  6  7]
[ 1  2  3 44  5  6  7]


In [28]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = a.view()
b[3] = 4444
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[   1    2    3 4444    5    6    7]
[   1    2    3 4444    5    6    7]
int32
int32


# 21) Check if Array Owns it's Data

In [29]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

None
[ 1  2  3  4  5  6  7  8  9 10]


# 22) Numpy array Shape

In [30]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

(2, 4)


In [31]:
import numpy as np
a = np.array([1,2,3,4,5],ndmin=5)
print(a.shape)

(1, 1, 1, 1, 5)


In [32]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a.shape)

(2, 4)


# 23) Reshaping numpy array

In [33]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(3,4)                                       # For 1-d array
print(f"This is 1-D array \n{a}")
print(f"This is 2-D array \n{b}")
print(b)

This is 1-D array 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
This is 2-D array 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(2,3,2)
print(f"This is 1-D array \n{a}")
print(f"This is 3-D array \n{b}")

This is 1-D array 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
This is 3-D array 
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# 24) To check reshaping wons data or not?

In [35]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(2,3,2)
print(f"This is 1-D array \n{a}")
print(f"This is 3-D array \n{b}")
print(b.base)

This is 1-D array 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
This is 3-D array 
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 25) Unknown dimension

In [36]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.reshape(2,5,-1))

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


# 26) Flattening to any dimension to 1-D array

In [37]:
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"This is the orginal array {a}")
print(f"This is after flattening the array into 1-D array{a.reshape(-1)}")

This is the orginal array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
This is after flattening the array into 1-D array[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 27) Extracting all the elements in the array by using "for" loop

In [38]:
import numpy as np                              # for 1- Dimensional array
a = np.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5
6


In [39]:
import numpy as np                              #for 2-Dimensional array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [40]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


# 28) Iterating array using nditer()

In [41]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8


In [42]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=["S"]):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [43]:
import numpy as np 
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(a[:,::2]):
    print(x)

1
3
5
6
8
10


# 29) Iterating array using ndenumerate()

In [44]:
import numpy as np
a = np.array([1,2,3,4,5])
for ix,x in np.ndenumerate(a):
    print(ix,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [45]:
import numpy as np 
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for iy,y in np.ndenumerate(a):
    print(iy,y)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# 30) Numpy Joining array

In [46]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
c = np.concatenate((a,b),axis=1)
print(c)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# 31) Numpy Stack Array

In [48]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
c = np.stack((a,b),axis=1)
print(c)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [49]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
c = np.vstack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [50]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
c = np.hstack((a,b))
print(c)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [51]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
c = np.dstack((a,b))
print(c)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


# 32) Splitting Numpy array

In [52]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)
print(a)
print(b)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [53]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,4)
print(a)
print(b)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [54]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,5)
print(a)
print(b)

[1 2 3 4 5 6]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [55]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = np.array_split(a,5)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [56]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
n = np.array_split(a, 3)
print(n)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# 33) Accessing the array_split()

In [57]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)
print(f"This is the original array{a}")
print(f"This is the splited array {b}")
print(f"To access the first array: {b[0]}")
print(f"To access the second array: {b[1]}")
print(f"To access the third array: {b[2]}")

This is the original array[1 2 3 4 5 6]
This is the splited array [array([1, 2]), array([3, 4]), array([5, 6])]
To access the first array: [1 2]
To access the second array: [3 4]
To access the third array: [5 6]


In [58]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a,3)
print(f"This is the original array \n{a}")
print(f"This is the splited array \n {b}")
print(f"To access the first array:\n {b[0]}")
print(f"To access the second array:\n {b[1]}")
print(f"To access the third array: \n{b[2]}")

This is the original array 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
This is the splited array 
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
To access the first array:
 [[1 2 3]
 [4 5 6]]
To access the second array:
 [[ 7  8  9]
 [10 11 12]]
To access the third array: 
[[13 14 15]
 [16 17 18]]


# 34) Numpy split() 

In [59]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.hsplit(a,3)
print(a)
print(b)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [60]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = np.vsplit(a,3)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [61]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a,3,axis=1)
print(b)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# 35)Searching Array

In [62]:
import numpy as np
a = np.array([1,2,3,4,5,4,4])
x = np.where(a==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [63]:
# Find the index where the value are even
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
x = np.where(a%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [64]:
#Find the index where the value are odd
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
x = np.where(a%2==1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# 36)Search Sorted

In [65]:
import numpy as np 
a = np.array([6,7,8,9])
x = np.searchsorted(a,7)
print(x)

1


In [66]:
import numpy as np
a = np.array([6,7,8,9])
x = np.searchsorted(a,7,side="right")
print(x)

2


In [67]:
import numpy as np
a = np.array([1,3,5,7])
x = np.searchsorted(a,[2,4,6])
print(x)

[1 2 3]


# 37) Sorting arrays

In [68]:
import numpy as np
a = np.array([3,2,0,1])
print(np.sort(a))

[0 1 2 3]


In [69]:
import numpy as np
a = np.array(["banana","cherry","apple"])
print(np.sort(a))

['apple' 'banana' 'cherry']


In [70]:
import numpy as np
a = np.array([True,False,True])
print(np.sort(a))

[False  True  True]


In [71]:
import numpy as np
a = np.array([[3,4,2],[5,1,6]])
print(np.sort(a))

[[2 3 4]
 [1 5 6]]


# 38) Filter array

In [72]:
import numpy as np
a = np.array([41,42,43,44])
x = [True,False,True,False]
b = a[x]
print(b)

[41 43]


In [73]:
import numpy as np
a = np.array([41,42,43,44])
filter_array=[]
for i in a:
    if i>42:
        filter_array.append(True)
    else:
        filter_array.append(False)
b = a[filter_array]
print(b)
        

[43 44]


In [74]:
# Create a filter array that will return only even elements from the orginal array
import numpy as np
a = np.array([1,2,3,4,5,6,7])
filter_array= []
for i in np.nditer(a):
    if i%2==0:
        filter_array.append(True)
    else:
        filter_array.append(False)
b = a[filter_array]
print(b)

[2 4 6]


# 39) Cretaing filter directly from array

In [75]:
import numpy as np
arr = np.array([41,42,43,44])
filter_array = arr>42
b = arr[filter_array]
print(filter_array)
print(b)

[False False  True  True]
[43 44]


In [76]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_array = arr%2==0
b = arr[filter_array]
print(filter_array)
print(b)

[False  True False  True False  True False]
[2 4 6]


       BY 
           NTS